language: shell
# The Google Cloud SDK on Travis is pretty old (2014). So if
# you want to use an up-to-date version, you have to install
# your own. This config is the bare minimum you'll need to
# get an updated version of the SDK + kubectl.
cache:
  directories:
  - $HOME/google-cloud-sdk
services:
- docker

env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: hCRt2PScEW1ghrJxX8FYsIF6g09CMSadDBHBIXkEKfZg+O9HJOhKOqpaItIZ5Y0a8x499C5vt/njm5DJTnGd2Knqpwp2Xd+r7eIy1fukpgNyLeFSyCIzkDoHnzQOHNsz+5B/3970oh7qLbyk0ldDr0wYfRWFNzBZq7CX43n9cMhRwRLCPMu7Htc00q3Bg09IQ6vbYckR5GYm+vbzh2PcYEso6NA62rlsLPoeFnuM6yTwAyHbHh+/2YT5705gyhK6Hjyr2B1oQ5u5NkTwhAsZH7j0RhsTRsGPfvddLLsAuiD55IC5UQvlx6hd2BDeXH7s9eLZyHj7n9FC9csBAfhOOx8YXSwvsNi+o9R63DKNyADShPUUdGswJ24z5x4T9ihv/9Vmal5f34wt/+d+e9BhC75fkBE/kLS9o0IN+8kB+xYSp52W9loDI4zmBVubrDN1DxkBmt0X2/xdAXUgHMekQLEsWmWxXEIvR/Cwf3VhByGxvGPD8DF/De415rtBb+SO1KBqjGD+X6oJt3zbt2jvQFaZmAkr+zsTF0BrL2e4ZgiFtsSvxPPH/Mvh7pZ09op24HxuWcDsGW8mSJ6F3FxRnM9RqvxyVMOnodJEQZ77dR7yZ9Zq7dK8KmiDnlzMk2oyY9cEdoB0fPkt4cJFjaPNycxWrfk3koZKqAxCAoSIzlA=
  - secure: U0uQKKJDpxNFaoVTXckveSq/J3Br4RA8yGfjRGGmJS3DyZ+xMztAEf0ODrpm2ZZsJ+tcol+HOoGv19gYeUxv/SwPm23ZUAxWWQFJXCVknX5gI0n1D/vSf2ig17o85nG9bM4xAudD0cWtIYJckUldYuNLAsOFiltNw5JSpm4W+PgDX7vJTFENzROlGdYDhnATpNzUaUgAQQT6wiMNL+LOW3MoTg+1jOReTUi7Iix+SnOu3z1JcYgXr3JJbn8M+xwiwFwOlSKQL42AIBE2y4JbtY6wNTAd/97EPZBJZmMbsHehNCTwFFS+fmDtMSpOiDq35GK0s437CjvpLMKuIjiM4wjTeESl8xOOaRnrsMCHpUMn2SeWz3ykhMRH7aXK37QtvmtuA70ztGmZUR5TBiUA7I2kaAoWXKaU3aL4joepb1FKM8nL6z/KGLpOBGUqN62iN6NaxpH859yQIlmSeyMhzVmLADkGlJaHR59+6ZqICc6YZaIqfSuECSs8SXwcJXJkX07Lw4oKbLOMDVzU6dLrTKI/1N73AdLnEoF9wuvgtdbCP4yJwuozHCbqg8zy6RN1iTaKqxAulQ7JOEtazmHmQ9OyBBz+kBrsAqfPHWz/+GDFnpJwqTTNoqQOe1hY79XVQwOMJGDXlskJ0LH/gtfbtmz3Q4zQrUQ61/kXVk1THVg=
  - secure: YQcc4HFwBjMZns+zoOVLztXPLe01zRyLteMNV/Fo3PNP8MSN+qWobmdweyDtUfAUINZDyZN1K8N6ABULnC0jABSGoRmB7cRtQ5KcL2Eu5hMSTzMAKAe+QeRyYPYN9lNdtMtAJuWPK+ysMkhVRSkFWyvjm8eQF21Xnl1AjamjthT8QM46pr97UiKMijnlCrnMCloPnYs0WOjdyM3Xv06oGPJOmN0TdMyn2XtUQkK5kxEVDNHGluBk+eU2dwJi49nmJNhqk2mySr1lsKZUd6LrtBoBIlSB5tM8xggGvtSlB10tF8TT3k0YrIzpwmTkMHjz5S9IOIuPkYmoiedKj+JLnX0FjrkleGL6J/xi51aHbrmn+iFZMXhcYmlupoGWyb94xueX2SXH3EcRymoOHmGqWp70OG/cXDCueF7+HFytCmPlqQ3jtQCRaIcQkEeHRKDPiA/O/k8mHnun7zTdswdAGGPWqqzVLLBaIleIXlZLRslwzw3xCGQ0FAK0tnMmQrISwMLqnFfxwrJgGyj3X0Ia/5PocU2GFJPGYSoaafW4dCASCo0PziD1NG0C+zSrhgsSa/eBKMWid9GIQb1HWY5y2tuBNKV339NrGlmNbR3O1adQbs77G/zQV0MSp3lAdsd13p8W6fHOEJIYIzqggMU3k2lsp8TcvHEaeK3JetiGBqM=

before_install:
  - sh google_cloud.sh
  # This line is critical. We setup the SDK to take precedence in our
  # environment over the old SDK that is already on the machine.
  - source $HOME/google-cloud-sdk/path.bash.inc
  #- gcloud components update kubectl
  - gcloud version
# Insert your own install + script below.
install:
  - sh gcr.sh
script: true

